export const packs = [
    {
        id: 1,
        name: 'Pack Jardin',
        prestations: [
            {
                id: 1,
                name: 'Prestation "Petit Jardin"',
                description: null,
                mowing: '1 Tonte de -250m²',
                hedgeTrimmer: '1 Taille de haie 1.20m de hauteur (Max)',
                bushPruning: '1 Taille de buisson',
                weeding: 'Désherbage de 2 massifs (Max)',
                brushCutter: 'Débroussailleuse',
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: null,
                price: 225,
                packs_id: 1
            },
            {
                id: 2,
                name: 'Prestation "Grand Jardin"',
                description: null,
                mowing: '1 Tonte de +250m² (600m² Max)',
                hedgeTrimmer: '1 Taille de haie 1.20m à 2m de hauteur (Max) et longueur 40m (Max)',
                bushPruning: '1 Taille de buisson',
                weeding: 'Désherbage de 3 massifs (Max)',
                brushCutter: 'Débroussailleuse',
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: null,
                price: 255,
                packs_id: 1
            },
            {
                id: 3,
                name: 'Prestation "Jardin Premium"',
                description: null,
                mowing: '1 Tonte de +600m² (800m² Max)',
                hedgeTrimmer: '1 Taille de haie 2m à 2.50m de hauteur (Max) et longueur 50m (Max)',
                bushPruning: '1 Taille de buisson',
                weeding: 'Désherbage de 6 massifs (Max)',
                brushCutter: 'Débroussailleuse',
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: '1 Petite plante + 2 Sachets de fleur/légumes offert',
                example: null,
                price: 320,
                packs_id: 1
            }
        ],
        formules: []
    },
    {
        id: 2,
        name: 'Pack Tonte',
        prestations: [
            {
                id: 4,
                name: 'Prestation "Petite Tonte"',
                description: 'Terrain de -250m²',
                mowing: '1 Tonte',
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: 'Débroussailleuse',
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: null,
                price: 170,
                packs_id: 2
            },
            {
                id: 5,
                name: 'Prestation "Grande Tonte"',
                description: 'Terrain de +250m² (600m² Max)',
                mowing: '1 Tonte',
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: 'Débroussailleuse',
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: null,
                price: 195,
                packs_id: 2
            },
            {
                id: 6,
                name: 'Prestation "Tonte Premium"',
                description: 'Terrain de +600m² (800m² Max)',
                mowing: '1 Tonte',
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: 'Débroussailleuse',
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: '2 Sachets de fleur ou légume offert',
                example: null,
                price: 215,
                packs_id: 2
            }
        ],
        formules: []
    },
    {
        id: 3,
        name: 'Pack Taille',
        prestations: [
            {
                id: 7,
                name: 'Prestation "Petite Taille"',
                description: 'Haie 1.20m de hauteur (Max) et 30m de longueur (Max)',
                mowing: null,
                hedgeTrimmer: 'Taille haie',
                bushPruning: 'Taille buisson',
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: null,
                price: 160,
                packs_id: 3
            },
            {
                id: 8,
                name: 'Prestation "Grande Taille"',
                description: 'Haie 1.20 à 2m de hauteur (Max) et 40m de longueur (Max)',
                mowing: null,
                hedgeTrimmer: 'Taille haie',
                bushPruning: 'Taille buisson',
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: null,
                price: 190,
                packs_id: 3
            },
            {
                id: 9,
                name: 'Prestation "Taille Premium"',
                description: 'Haie 2 à 2.50m de hauteur (Max) et 50m de longueur (Max)',
                mowing: null,
                hedgeTrimmer: 'Taille haie',
                bushPruning: 'Taille buisson',
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: '1 petite plante offerte',
                example: null,
                price: 210,
                packs_id: 3
            }
        ],
        formules: []
    },
    {
        id: 4,
        name: 'Pack Désherbage',
        prestations: [
            {
                id: 10,
                name: 'Prestation "Petit Désherbage"',
                description: null,
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: 'Désherbage de 3 massifs (Max)',
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: null,
                price: 150,
                packs_id: 4
            },
            {
                id: 11,
                name: 'Prestation "Grand Désherbage"',
                description: null,
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: 'Désherbage de 5 massifs (Max)',
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: null,
                price: 175,
                packs_id: 4
            },
            {
                id: 12,
                name: 'Prestation "Désherbage Premium"',
                description: null,
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: 'Désherbage de tous vos massifs',
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: '1 Petite plante offerte',
                example: null,
                price: 195,
                packs_id: 4
            }
        ],
        formules: []
    },
    {
        id: 5,
        name: 'Pack Massif',
        prestations: [
            {
                id: 13,
                name: 'Prestation "Petit Massif"',
                description: 'Les matériaux et les plantes sont payables d\'avance. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: 'Plantation de fleur et/ou petit arbuste (5Max)',
                tarpaulin: 'Pose de bâche avec agrafes (5m linéaire Max)',
                mulching: 'Paillage (copeaux, gravillons,...)',
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: 'exemple: 3 fleurs, 2 arbustes',
                price: 170,
                packs_id: 5
            },
            {
                id: 14,
                name: 'Prestation "Grand Massif"',
                description: 'Les matériaux et les plantes sont payables d\'avance. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: 'Plantation de fleur et/ou petit arbuste (10Max)',
                tarpaulin: 'Pose de bâche avec agrafes (10m linéaire Max)',
                mulching: 'Paillage (copeaux, gravillons,...)',
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: 'exemple: 7 fleurs, 3 arbustes',
                price: 205,
                packs_id: 5
            },
            {
                id: 15,
                name: 'Prestation "Massif Premium"',
                description: 'Les matériaux et les plantes sont payables d\'avance. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: 'Plantation de fleur et/ou petit arbuste (15Max)',
                tarpaulin: 'Pose de bâche avec agrafes (15m linéaire Max)',
                mulching: 'Paillage (copeaux, gravillons,...)',
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: '1 Petite plante d\'intérieur offerte',
                example: 'exemple: 5 fleurs, 10 arbustes',
                price: 240,
                packs_id: 5
            }
        ],
        formules: []
    },
    {
        id: 6,
        name: 'Pack Plantation',
        prestations: [
            {
                id: 16,
                name: 'Prestation "Petite Plantation"',
                description: 'Les plantes sont payables d\'avance. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: 'Plantation de fleur et/ou petit arbuste (10Max)',
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: 'exemple: 3 fleurs, 7 arbustes',
                price: 150,
                packs_id: 6
            },
            {
                id: 17,
                name: 'Prestation "Grande Plantation"',
                description: 'Les plantes sont payables d\'avance. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: 'Plantation de fleur et/ou petit arbuste (20Max)',
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: null,
                example: 'exemple: 13 fleurs, 7 arbustes',
                price: 170,
                packs_id: 6
            },
            {
                id: 18,
                name: 'Prestation "Plantation Premium"',
                description: 'Les plantes sont payables d\'avance. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: 'Plantation de fleur et/ou petit arbuste (30Max)',
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: 'Souffleur',
                pickup: 'Ramassage des déchets verts',
                gifts: '1 Petite plante d\'intérieur offerte',
                example: 'exemple: 15 fleurs, 15 arbustes',
                price: 190,
                packs_id: 6
            }
        ],
        formules: []
    },
    {
        id: 7,
        name: 'Pack Jardinière / Bac à fleurs',
        prestations: [
            {
                id: 19,
                name: 'Prestation "Jardinière potagère"',
                description: 'Matériaux et végétaux sont payables d\'avance pour le contenu des jardinières. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: '3 Jardinières avec support (2 à 3 Plants par jardinière Max)',
                aromaticSeasonalFlower: 'Aromatiques, petits légumes, etc... (En fonction de la saison)',
                soil: 'Terre aromatique / Terre de potager',
                fertilizer: 'Engrais',
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: null,
                pickup: null,
                gifts: null,
                example: null,
                price: 160,
                packs_id: 7
            },
            {
                id: 20,
                name: 'Prestation "Jardinière de fleurs"',
                description: 'Matériaux et végétaux sont payables d\'avance pour le contenu des jardinières. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: '3 Jardinières (2 à 3 Plants par jardinière Max)',
                aromaticSeasonalFlower: 'Fleurs de saison ou vivaces',
                soil: 'Terre de jardinières / Terre de vivaces',
                fertilizer: 'Engrais',
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: null,
                pickup: null,
                gifts: null,
                example: null,
                price: 170,
                packs_id: 7
            },
            {
                id: 21,
                name: 'Prestation "Bac à fleurs / Potager Premium"',
                description: 'Matériaux et végétaux sont payables d\'avance pour le contenu des jardinières. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: '3 Bacs en bois ou en plastique (2 à 3 Plants par bac Max)',
                aromaticSeasonalFlower: 'Fleurs de saison et/ou Petit arbuste et/ou potager (3Max)',
                soil: 'Terre universel',
                fertilizer: 'Engrais',
                composition: null,
                brushing: null,
                washing: null,
                photo: null,
                blower: null,
                pickup: null,
                gifts: '1 Sachet de bulbes ou fleurs offert',
                example: 'exemple: 1 bac fleur, 1 bac arbuste et 1 bac potager',
                price: 240320,
                packs_id: 7
            }
        ],
        formules: []
    },
    {
        id: 8,
        name: 'Pack Sépultures',
        prestations: [
            {
                id: 22,
                name: 'Prestation "Composition"',
                description: 'Matériaux et vététaux sont payables d\'avance pour le contenu de la composition. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: '1 Composition florale de votre choix',
                brushing: null,
                washing: null,
                photo: '1 Photo de votre composition une fois réalisé',
                blower: null,
                pickup: null,
                gifts: null,
                example: null,
                price: 90,
                packs_id: 8
            },
            {
                id: 23,
                name: 'Prestation "Entretien"',
                description: null,
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: null,
                brushing: '1 Brossage, rinçage et séchage',
                washing: '1 Lavage des ornements',
                photo: '1 Photo de la sépulture une fois réalisé',
                blower: null,
                pickup: null,
                gifts: null,
                example: null,
                price: 100,
                packs_id: 8
            },
            {
                id: 24,
                name: 'Prestation "Sépultures Premium"',
                description: 'Matériaux et vététaux sont payables d\'avance pour le contenu de la composition. Merci',
                mowing: null,
                hedgeTrimmer: null,
                bushPruning: null,
                weeding: null,
                brushCutter: null,
                planting: null,
                tarpaulin: null,
                mulching: null,
                planters: null,
                aromaticSeasonalFlower: null,
                soil: null,
                fertilizer: null,
                composition: '1 Composition florale de votre choix',
                brushing: '1 Brossage, rinçage et séchage',
                washing: '1 Lavage des ornements',
                photo: '1 Photo de la sépulture une fois réalisé',
                blower: null,
                pickup: null,
                gifts: '1 Tampon supplémentaire offert sur la carte de fidélité',
                example: null,
                price: 155,
                packs_id: 8
            }
        ],
        formules: []
    },
    {
        id: 9,
        name: 'Formule individuelles',
        prestations: [],
        formules: [{
            id: 1,
            name: 'Tonte',
            description: '1 Tonte avec un terrain 600m² (Max)',
            price: 27,
            packs_id: 9
        },
        {
            id: 2,
            name: 'Taille',
            description: '1 Taille buisson / arbre / haie d\'une hauteur de 2m (Max)',
            price: 33,
            packs_id: 9
        },
        {
            id: 3,
            name: 'Désherbage',
            description: 'Désherbage',
            price: 27,
            packs_id: 9
        },
        {
            id: 4,
            name: 'Massif',
            description: 'Plantation de fleur et/ou petit arbuste + Pose de bâche avec agrafes + Paillage (copeaux, gravillons, ...)',
            price: 27,
            packs_id: 9
        },
        {
            id: 5,
            name: 'Plantation',
            description: 'Plantation de fleur et/ou petit arbuste',
            price: 23,
            packs_id: 9
        },
        {
            id: 6,
            name: 'Jardinières fleurie',
            description: '1 "Jardinière Fleurie" garnis avec support',
            price: 65,
            packs_id: 9
        },
        {
            id: 7,
            name: 'Jardinières potagère',
            description: '1 “Jardinière potagère" garnis avec support',
            price: 55,
            packs_id: 9
        },
        {
            id: 8,
            name: 'Débroussaillage',
            description: 'Débroussailleuse',
            price: 23,
            packs_id: 9
        },
        {
            id: 9,
            name: 'Souffleur',
            description: 'Souffleur',
            price: 23,
            packs_id: 9
        },
        {
            id: 10,
            name: 'Ramassage',
            description: 'Ramassage des déchets verts',
            price: 27,
            packs_id: 9
        },
        {
            id: 11,
            name: 'Bois',
            description: 'Stockage du bois',
            price: 27,
            packs_id: 9
        },
        {
            id: 12,
            name: 'Arrosage',
            description: 'Arrosage de votre jardin, de vos plantes, de votre potager, de massif(s)',
            price: 11,
            packs_id: 9
        },
        {
            id: 13,
            name: 'Déneigeage',
            description: 'Déneigeage',
            price: 27,
            packs_id: 9
        }]
    }
];

export const tags = [
    {
        id: 1,
        name: 'Jardin'
    },
    {
        id: 2,
        name: 'Tonte'
    },
    {
        id: 3,
        name: 'Taille'
    },
    {
        id: 4,
        name: 'Désherbage'
    },
    {
        id: 5,
        name: 'Massif'
    },
    {
        id: 6,
        name: 'Plantation'
    },
    {
        id: 7,
        name: 'Jardinière / Bac à fleurs'
    },
    {
        id: 8,
        name: 'Sépultures'
    },
    {
        id: 9,
        name: 'Débroussaillage'
    },
    {
        id: 10,
        name: 'Souffleur'
    },
    {
        id: 11,
        name: 'Ramassage'
    },
    {
        id: 12,
        name: 'Bois'
    },
    {
        id: 13,
        name: 'Arrosage'
    },
    {
        id: 14,
        name: 'Déneigeage'
    }
];